description: "模型繁體中文回應測試"

prompts:
  - file://./prompts/prompt_basic.yaml
  # - file://./prompts/prompt_tool.yaml

providers:
  # - file://./providers/llama2.yaml
  - file://./providers/breeze.yaml
  # - file://./providers/Llama-3.2-3B-F1.yaml
  # - file://./providers/gpt-4o-mini.yaml
  # - file://./providers/llama3_1.yaml
  # - file://./providers/breeze2.yaml
  - file://./providers/gemma3.yaml

  

tests: 
  - file://./tests/generate.py:basic_eval
  # - file://./tests/generate.py:tool_eval
